function [f, value] = importPulse(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [VARNAME2, VARNAME3] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [VARNAME2, VARNAME3] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [VarName2, VarName3] = importfile("/Users/silasstuhldreier/Documents/Studium/Studium Engineering Acoustics/2nd Semester/34860 Advanced Acoustics/LAB/GITHUB/datas/Lab_4/Dipole_1.txt", [84, 107]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Apr-2025 12:11:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [84, 107];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2", "VarName3"];
opts.SelectedVariableNames = ["VarName2", "VarName3"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
f = tbl.VarName2';
value = tbl.VarName3';
end