function [f, Hxy] = importHxy(filename, dataLines)
%  Import Frequency response and frequency vector from PULSE Measurement .txt file
%  [F, Hxy] = IMPORTFILE(FILENAME) reads data from text
%  
%  Returns frequency response as a complex collum vector and a frequency vector 
%  f = frequency vector
%  Hxy = frequency response
%  
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Mar-2025 17:06:48
% alternated by Silas on 09-Mar-2025

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [84, 3284];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["f", "Var1", "Var2", "Var3"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
% f = tbl.f;
% Var1 = tbl.Var1;

f = tbl.Var1;
Var2 = tbl.Var2;
Var3 = tbl.Var3;

Hxy=Var2+1j.*Var3;

end